version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.14.3
    steps:
      - checkout
      - run: GMENV_LDAP_USERNAME="${NEXUS_USER}" GMENV_LDAP_PASSWORD="${NEXUS_PASS}" test/run.sh

workflows:
  version: 2
  build:
    jobs:
      - test
        # filters:
        #   tags:
        #     ignore: /.*/
        #   branches:
        #     only: master
