#!/usr/bin/env bash
set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${GMENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine GMENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine GMENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  GMENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n ${GMENV_ROOT} ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine GMENV_ROOT";
else
  GMENV_ROOT="${GMENV_ROOT%/}";
fi;
export GMENV_ROOT;

if [ -n "${GMENV_HELPERS:-""}" ]; then
  log 'debug' 'GMENV_HELPERS is set, not sourcing helpers again';
else
  [ "${GMENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${GMENV_ROOT}/lib/helpers.sh";
  if source "${GMENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${GMENV_ROOT}/lib/helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${GMENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${GMENV_ROOT}/${dir}', not adding it again";;
    *) 
      log 'debug' "\$PATH does not contain '${GMENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${GMENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

[ "${#}" -gt 1 ] && log 'error' 'usage: gmenv use [<version>]';

[ -d "${GMENV_ROOT}/versions" ] \
  || log 'error' 'No versions of greymatter installed. Please install one with: gmenv install';

declare requested="${1:-""}";

log debug "Resolving version with: gmenv-resolve-version ${requested}";
declare resolved="$(gmenv-resolve-version ${requested})";

declare version="${resolved%%\:*}";
declare regex="${resolved##*\:}";

log 'debug' "Searching ${GMENV_ROOT}/versions for latest version matching ${regex}";
declare version="$(\ls "${GMENV_ROOT}/versions" \
  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
  | grep -e "${regex}" \
  | head -n 1
)";

[ -n "${version}" ] \
  && log 'debug' "Found version: ${version}" \
  || log 'error' "No installed versions of greymatter matched '${1}'";

target_path="${GMENV_ROOT}/versions/${version}";
[ -f "${target_path}/greymatter" ] \
  || log 'error' "Version directory for ${version} is present, but the greymatter binary is not! Manual intervention required.";
[ -x "${target_path}/greymatter" ] \
  || log 'error' "Version directory for ${version} is present, but the greymatter binary is not executable! Manual intervention required.";

log 'info' "Switching default version to v${version}";
version_file="${GMENV_ROOT}/version";
log 'debug' "Writing \"${version}\" to \"${version_file}\"";
echo "${version}" > "${version_file}" \
  || log 'error' "Switch to v${version} failed";

if [ "${version_file}" != "$(gmenv-version-file)" ]; then
  log 'warn' "Default version file overridden by $(gmenv-version-file), changing the default version has no effect";
fi;

greymatter version 1>/dev/null \
  || log 'error' "'greymatter version' failed. Something is seriously wrong";
log 'info' "Switching completed";