name: Changelog CI

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v0.6.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}